// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	"github.com/go-kit/kit/transport/grpc"
	"github.com/king19800105/go-kit-learn/demo5/pkg/endpoint"
	"github.com/king19800105/go-kit-learn/demo5/pkg/grpc/pb"
)


type grpcServer struct {
	create grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.OrderServer {
	return &grpcServer{
		makeCreateHandler(endpoints, options["Create"]),
	}
}
